logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  application:
    name: DummyTalk_BE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:

        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  data:
    redis:
      host: ${DB_HOST}
      port: 6379
  sql:
    init:
      mode: never

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  mail:
    host: ${MAIL_SENDER_HOST}
    port: 587
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
      auth-code-expiration-millis: 300000

  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

management:
  endpoint:
    # 1. Prometheus 엔드포인트 자체를 활성화합니다. (Spring Boot 3.x 권장 방식)
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        # 2. 웹을 통해 노출할 Actuator 엔드포인트를 지정합니다.
        include: health, info, prometheus